<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
        <a class="navbar-brand" href="#/">Phalcon Admin Example</a>
    </div>

    <div class="navbar-default sidebar" role="navigation">
        <div class="sidebar-nav navbar-collapse">
            <ul class="nav" id="side-menu">
                <li>
                    <a href="#/dashboard"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                </li>
                <li>
                    <a href="#/uploads">
                        <i class="fa fa-bar-chart-o fa-fw"></i> Image Uploads
                    </a>
                </li>
                <li>
                    <a href="#/slider">
                        <i class="fa fa-bar-chart-o fa-fw"></i> Slider Settings
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>