<ul class="nav navbar-nav navbar-right">
    <li><a href="#">Welcome, {{email}}</a></li>
    <li>
        <img src="/img/example.jpg" alt="..." style="height: 50px;" class="img-circle">
    </li>
    <li class="dropdown" dropdown>
        <a href="#" class="dropdown-toggle" dropdown-toggle role="button" aria-expanded="false">
            <span class="caret"></span>
        </a>
        <ul class="dropdown-menu" >
            <li><a href="#dashboard">Dashboard</a></li>
            <li><a href="#" ng-click="logout()">Logout</a></li>
        </ul>
    </li>
</ul>