<form ng-submit="login()" role="form">
    <div class="modal-header">
        <h3 class="modal-title">Sign In!</h3>
    </div>
    <div ng-show="error" class="alert alert-danger">{{error}}</div>
    <div class="modal-body">
        <div class="form-group">
            <label for="email">Email address</label>
            <input type="email" class="form-control" id="email" ng-model="email" placeholder="Enter email" required="true">
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" class="form-control" id="password" ng-model="password" placeholder="Password" required="true">
        </div>
        <div class="checkbox">
            <label>
                <input type="checkbox" ng-model="saveMe"> Save me
            </label>
        </div>
    </div>
    <div class="modal-footer">
        <button class="btn btn-success" type="submit">Sign In</button>
        <button class="btn btn-warning" ng-click="cancel()">Cancel</button>
    </div>
</form>