<div class="modal-header">
    <h3 class="modal-title">Sign Up!</h3>
</div>
<div class="modal-body">
    <div class="form-group">
        <label for="email">Email address</label>
        <input type="email" class="form-control" id="email" placeholder="Enter email">
    </div>
    <div class="form-group">
        <label for="password">Password</label>
        <input type="password" class="form-control" id="password" placeholder="Password">
    </div>
    <div class="form-group">
        <label for="password">Confirm Password</label>
        <input type="password" class="form-control" id="confirm-password" placeholder="Confirm Password">
    </div>
</div>
<div class="modal-footer">
    <button class="btn btn-primary" ng-click="registration()">Sign Up</button>
    <button class="btn btn-warning" ng-click="cancel()">Cancel</button>
</div>