<div ng-controller="SliderCtrl">
    <div style="height: 500px">
        <carousel interval="myInterval">
            <slide ng-repeat="slide in slides" active="slide.active">
                <img ng-src="{{slide.image}}" style="margin:auto;">
                <div class="carousel-caption">
                    <h4>Slide {{$index + 1}}</h4>
                    <p>{{slide.text}}</p>
                </div>
            </slide>
        </carousel>
    </div>
    <div class="row">
        <div class="col-md-6">
            <button type="button" class="btn btn-info" ng-click="addSlide()">Add Slide</button>
        </div>
        <div class="col-md-6">
            Interval, in milliseconds: <input type="number" class="form-control" ng-model="myInterval">
            <br />Enter a negative number or 0 to stop the interval.
        </div>
    </div>
</div>

<!-- Page Content -->
<div class="container">

    <hr class="featurette-divider">

    <!-- First Featurette -->
    <div class="featurette" id="about">
        <img class="featurette-image img-circle img-responsive pull-right" src="http://placehold.it/500x500">
        <h2 class="featurette-heading">This First Heading
            <span class="text-muted">Will Catch Your Eye</span>
        </h2>
        <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
    </div>

    <hr class="featurette-divider">

    <!-- Second Featurette -->
    <div class="featurette" id="services">
        <img class="featurette-image img-circle img-responsive pull-left" src="http://placehold.it/500x500">
        <h2 class="featurette-heading">The Second Heading
            <span class="text-muted">Is Pretty Cool Too.</span>
        </h2>
        <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
    </div>

    <hr class="featurette-divider">

    <!-- Third Featurette -->
    <div class="featurette" id="contact">
        <img class="featurette-image img-circle img-responsive pull-right" src="http://placehold.it/500x500">
        <h2 class="featurette-heading">The Third Heading
            <span class="text-muted">Will Seal the Deal.</span>
        </h2>
        <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
    </div>

    <hr class="featurette-divider">

    <footer>
        <div class="row">
            <div class="col-lg-12">
                <p>Copyright &copy; Phalcone Test 2015</p>
            </div>
        </div>
    </footer>
</div>